### ISSUE TITLE
add an uninstaller or instructions to do so for users

### ISSUE THREAD

**Issue by 573** [aformatik/codchi#29]
Very cool project !

![grafik](https://github.com/user-attachments/assets/547080a9-399c-4be1-bb65-7c4996cdf237)

When running `codchi.msix` on a Windows machine first I'm being presented with is this dialog saying:
• Uses all system resources
• Write registry entries and files that are not cleaned up on uninstall

It might lower the onboarding barrier especially for enterprise users or complete nixos newbies to have a more assertive list here i. e. adding a link to uninstall instructions or just providing the functionality. As well as a data governance and privacy policy document asap would be important to keep potential adopters close. I'm writing this because I see much potential in *codchi* and would very much consider to use it as a low barrier alternative to NixOS-WSL in the future.

**Comment by 573** [comment]
Some links for codchi newbs like me:
- https://github.com/aformatik/codchi/blob/cfb62fd3c04937a8effbc9968480920e5582abe9/build/build-rust-package.nix

**Comment by htngr** [comment]
Thanks!

Sadly we don't have much control over the installation dialog because its controlled by Windows. The MSIX packaging format doesn't really allow more granular permissions, to interact with WSL from within a MSIX package, we need "Uses all system resources" (although maybe we could remove the registry permission). Maybe someone can prove me wrong?

We'll also add uninstallation instructions in the future, but in short its just one click in the Windows Appcenter. Also, if you had code machines, `codchi delete` them before.

> data governance and privacy policy document
What do you mean by that?

**Comment by 573** [comment]
@htngr thanks for the further details, the second part of my request regarding data usage related to the msix installer more as on first glance it wasn't directly clear to me what changes to the host system the installation involved.
Looking at https://github.com/aformatik/codchi/tree/cfb62fd3c04937a8effbc9968480920e5582abe9/build/msix at bit deeper alleviates any concerns in that direction for me.
